language: ruby
rvm:
  - 2.2.1
git:
  submodules: false
notifications:
  email:
    recipients:
      - wordman05@gmail.com
      - spyguy57@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
  - master
addons:
  code_climate:
    repo_token: 0dfb776be0669c04ab483215160fa41bc04440eac516832af747aeba5c037060
  apt:
    packages:
install:
  - bundle install
script:
  - chmod +x ./build/build.sh
  - ./build/build.sh
  - rake test --trace
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: spygadgetbox
  skip_cleanup: true
